### ISSUE TITLE
This workflow can work for sample.fastq.gz using zymo database, however, Not work in hpvc database. 

### ISSUE THREAD

**Issue by wdiao-zju** [epi2me-labs/wf-metagenomics#2]
This workflow can work for sample.fastq.gz using zymo database, however, Not work in hpvc database. I wanna know which cause this error. Thanks!

It can work as follows:

```bash
OUTPUT=output
nextflow run main.nf \
  -c my_config.cfg \
  -w ${OUTPUT}/workspace \
  -profile standard \
  --fastq test_data/sample.fastq.gz \
  --db_path test_data/db_store/zymo \
  --db_prefix zymo \
  --out_dir ${OUTPUT} \
  --threads 40 \
  --wfversion latest
```

It can NOT work as follows:  

```bash
OUTPUT=output
nextflow run main.nf \
  -c my_config.cfg \
  -w ${OUTPUT}/workspace \
  -profile standard \
  --fastq test_data/sample.fastq.gz \
  --db_path test_data/db_store \
  --db_prefix hpvc \
  --out_dir ${OUTPUT} \
  --threads 40 \
  --wfversion latest
```

Error info

```
Error executing process > 'pipeline:generateMaster (1)'

Caused by:
  Process `pipeline:generateMaster (1)` terminated with an error exit status (1)

Command executed:

  generate_master_table.py analysis/read_classifications.tsv seqs.txt analysis --split "fungi:phylum:4751 bacteria:phylum:2 viruses:phylum:10239 else:superkingdom:" --human
  generate_report.py analysis/read_classification_master.tsv seqs.txt
  date

Command exit status:
  1

Command output:
  (empty)

Command error:
  /home/epi2melabs/conda/lib/python3.8/site-packages/ncbitaxonomy/ncbi_taxonomy/ncbiquery.py:233: UserWarning: taxid 2588707 was translated into 2487422
    warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
  Traceback (most recent call last):
    File "/root/project/nanopore/wf-metagenomics/bin/generate_master_table.py", line 304, in <module>
      main()
    File "/root/project/nanopore/wf-metagenomics/bin/generate_master_table.py", line 277, in main
      assignments = by_rule(tax_groups, rules=split_by_rule)
    File "/root/project/nanopore/wf-metagenomics/bin/generate_master_table.py", line 211, in by_rule
      for rule in _generate_rules(rules):
    File "/root/project/nanopore/wf-metagenomics/bin/gene
```

My enviroment infomation 

```
Python version 3.8.10
nextflow version 21.04.0

 project name: epi2me-labs/wf-metagenomics repository  : https://github.com/epi2me-labs/wf-metagenomics
 local path  : /root/.nextflow/assets/epi2me-labs/wf-metagenomics
 main script : main.nf
 revisions   : 

 * master (default)
   prerelease
   v0.0.1 [t]
   v0.0.2 [t]
   v0.1.0 [t]
   v0.2.0 [t]
```

**Comment by sagrudd** [comment]
Hello @wdiao-zju - the wf-metagenomics workflow has been updated; are you still facing this issue? 

The updated workflow now uses the kraken2 software for taxonomic assignment - there is a healthy collection of indices that can be used available at e.g. https://benlangmead.github.io/aws-indexes/k2

Please let us know if you are still facing problems with running your sequence analysis.

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? We'll close this ticket on the assumption things are now resolved.
