### ISSUE TITLE
[Bug]: No such variable: recursion 

### ISSUE THREAD

**Issue by alexahess** [epi2me-labs/wf-metagenomics#30]
### What happened?

Hello, 

I'm trying to run the metagenomics workflow, but I'm running into some issues. 

When I try to run it I get this error: 
`No such variable: recursion`
`--check script '/usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/main.nf' at line: 10`

Do any of you have an idea how to fix this? I tried running another workflow and it worked. 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

nextflow run epi2me-labs/wf-metagenomics --version

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

2.06

### Relevant log output

```shell
Dec-13 12:22:29.421 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-metagenomics --version
Dec-13 12:22:29.477 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.0
Dec-13 12:22:30.200 [main] DEBUG nextflow.scm.AssetManager - Git config: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-metagenomics.git
Dec-13 12:22:30.213 [main] DEBUG nextflow.scm.AssetManager - Git config: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-metagenomics.git
Dec-13 12:22:30.281 [main] INFO  nextflow.cli.CmdRun - Launching `epi2me-labs/wf-metagenomics` [compassionate_watson] - revision: f5d1e16131 [master]
Dec-13 12:22:30.751 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config
Dec-13 12:22:30.752 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config
Dec-13 12:22:30.758 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-13 12:22:30.890 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/usr/lib/ont-nextflow/plugins
Dec-13 12:22:30.891 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Dec-13 12:22:30.899 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec-13 12:22:30.900 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec-13 12:22:30.903 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Dec-13 12:22:30.911 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Dec-13 12:22:30.956 [main] DEBUG nextflow.Session - Session uuid: 31dc2dfe-ad0c-490a-ac15-54d9e025947d
Dec-13 12:22:30.956 [main] DEBUG nextflow.Session - Run name: compassionate_watson
Dec-13 12:22:30.956 [main] DEBUG nextflow.Session - Executor pool size: 16
Dec-13 12:22:30.979 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.10.0 build 5641
  Created: 11-11-2021 18:37 UTC (18:37 BST)
  System: Linux 5.15.0-56-generic
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu220.04
  Encoding: UTF-8 (UTF-8)
  Process: 47086@GXB03790 [127.0.0.1]
  CPUs: 16 - Mem: 62.7 GB (54.6 GB) - Swap: 8 GB (8 GB)
Dec-13 12:22:30.989 [main] DEBUG nextflow.Session - Work-dir: /home/grid/work [ext2/ext3]
Dec-13 12:22:31.038 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, AwsBatchExecutor, IgExecutor]
Dec-13 12:22:31.049 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-13 12:22:31.064 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-13 12:22:31.128 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Dec-13 12:22:31.189 [main] DEBUG nextflow.Session - Session start invoked
Dec-13 12:22:31.192 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /home/grid/output/execution/trace.txt
Dec-13 12:22:31.201 [main] DEBUG nextflow.Session - Using default localLib path: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/lib
Dec-13 12:22:31.203 [main] DEBUG nextflow.Session - Adding to the classpath library: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/lib
Dec-13 12:22:31.204 [main] DEBUG nextflow.Session - Adding to the classpath library: /usr/lib/ont-nextflow/assets/epi2me-labs/wf-metagenomics/lib/nfcore_external_java_deps.jar
Dec-13 12:22:32.186 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-13 12:22:33.485 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: recursion for class: nextflow.NextflowMeta
Possible solutions: version
Dec-13 12:22:33.496 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: recursion for class: nextflow.NextflowMeta
Possible solutions: version
	at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2862)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3854)
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:219)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496)
	at nextflow.NextflowMeta$Preview.propertyMissing(NextflowMeta.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:883)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2864)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3854)
	at groovy.lang.GroovyObject.setProperty(GroovyObject.java:61)
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496)
	at Script_f0844270.runScript(Script_f0844270:10)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:309)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

**Comment by thecorz** [comment]
You are probably running the workflow with an old version of nextflow, where `recursion` was not implemented yet. Update nextflow to the latest version and try again.

**Comment by alexahess** [comment]
Sorry, I am not very used to working with Nextflow or the ont-workflows yet. 

I tried running `nextflow self-update` and get the message `self-update is disabled in ont-nextflow`. 

Current version we're running is version 21.10.0.

**Comment by thecorz** [comment]
Maybe uninstall and install again? or use the pure nextflow library, not the `ont-nextflow` library

**Comment by stas-malavin** [comment]
Installing a current version from ```www.nextflow.io``` helps.
