### ISSUE TITLE
Minimap2 usage

### ISSUE THREAD

**Issue by eparisis** [epi2me-labs/wf-metagenomics#32]
### What happened?

I am trying to use this workflow with `--classifier minimap2` but I am unsure on how to correctly use this option. I try running: 
```bash 
nextflow run epi2me-labs/wf-metagenomics --fastq ../anonymous_reads_sample_0.fq.gz --classifier minimap2 --reference archaea.fna --out_dir test --threads 20
```
In this test run I created a fasta file with complete archaeal genomes. I am using simulated reads so I know that in my fastq file I have some archaeal genomes present. I also tried running it with a smaller reference file with viruses. 

Every time I run it, the workflow "completes successfully" but the output files are empty. I only get an empty `wf-metagenomics-report.html` file in the output directory. Also, it only runs for just a few minutes compared to the kraken2 workflow.

So my question is what is the right way to use this workflow with minimap2 and what would the command to execute look like?

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v2.0.6

### Relevant log output

```shell
--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.0.6-ga67b931.
--------------------------------------------------------------------------------
Checking inputs.
Checking custom reference exists
Checking custom reference index exists
Checking fastq input.
Single file input detected.
executor >  local (9)
[fb/c1a177] process > minimap_pipeline:unpackTaxonomy         [100%] 1 of 1 ✔
[ca/8e1795] process > minimap_pipeline:combineFilterFastq (1) [100%] 1 of 1 ✔
[b4/eb5976] process > minimap_pipeline:minimap (1)            [100%] 1 of 1 ✔
[d4/3341c0] process > minimap_pipeline:getVersions            [100%] 1 of 1 ✔
[a5/5d690a] process > minimap_pipeline:getParams              [100%] 1 of 1 ✔
[26/eb843b] process > minimap_pipeline:makeReport             [100%] 1 of 1 ✔
[b8/4363d7] process > minimap_pipeline:output (3)             [100%] 3 of 3 ✔
Completed at: 03-Jan-2023 09:51:44
Duration    : 4m
CPU hours   : 0.3
Succeeded   : 9
```

**Comment by eparisis** [comment]
Thanks for the quick reply. I tried running the newer version but now I get the following error code and the pipeline doesn't finish:
```bash
executor >  local (7)
[5e/f95625] process > minimap_pipeline:unpackTaxonomy         [100%] 1 of 1 ✔
[dd/c16e3c] process > minimap_pipeline:combineFilterFastq (1) [100%] 1 of 1 ✔
[61/779f72] process > minimap_pipeline:minimap (1)            [100%] 1 of 1, failed: 1 ✘
[bc/ce1b17] process > minimap_pipeline:getVersions            [100%] 1 of 1 ✔
[14/e72de3] process > minimap_pipeline:getParams              [100%] 1 of 1 ✔
[-        ] process > minimap_pipeline:makeReport             -
[88/bc899c] process > minimap_pipeline:output (2)             [100%] 2 of 2 ✔
Error executing process > 'minimap_pipeline:minimap (1)'

Caused by:
  Process `minimap_pipeline:minimap (1)` terminated with an error exit status (1)

Command executed:

  minimap2 -t "8"  -ax map-ont "archaea.fna" "anonymous_reads.fastq"     | samtools view -h -F 2304 -     | format_minimap2.py - -o "anonymous_reads.minimap2.assignments.tsv" -r "ref2taxid.targloci.tsv"     | samtools sort -o "anonymous_reads.bam" -
  samtools index "anonymous_reads.bam"
  awk -F '\t' '{print $3}' "anonymous_reads.minimap2.assignments.tsv" > taxids.tmp
  taxonkit         --data-dir "taxonomy_dir"         lineage -R taxids.tmp         | aggregate_lineages.py -p "anonymous_reads.minimap2"
  file1=`cat *.json`
  echo "{"'"anonymous_reads"'": "$file1"}" >> temp
  cp "temp" "anonymous_reads.json"

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::mm_idx_gen::16.700*1.49] collected minimizers
  [M::mm_idx_gen::18.285*2.02] sorted minimizers
  [M::main::18.285*2.02] loaded/built the index for 898 target sequence(s)
  [M::mm_mapopt_update::19.745*1.95] mid_occ = 163
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 898
  [M::mm_idx_stat::20.574*1.91] distinct minimizers: 81971926 (47.58% are singletons); average occurrences: 3.164; average spacing: 5.356; total length: 1389285603
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'NZ_CP007264.1'
```

**Comment by sarahjeeeze** [comment]
I guess that ID is not in the provided ref2taxid file. If you are using your own reference fasta, you will also need to provide the parameter '--ref2taxid' which is a TSV file with fasta sequence id to tax id mappings eg. 
```
NG_012432.1	162394
NG_012432.1	162394
NG_013120.1	4952
```
I will look in to improving the documentation to make this clearer, let me know if you need any guidance on creating that file.

**Comment by sarahjeeeze** [comment]
You should be able to get the relevant file here https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/ - I think you want the `nucl_wgs.accession2taxid.gz`. You will then need to parse it to get it in the format required for the ref2taxid parameter which you can do in bash with eg. `cut -f 2,3 nucl_wgs.accession2taxid.tsv > ref2taxid.tsv`.

It should contain all the ID's so you can just use as it but if you do want to cross reference with your fasta file you could do something like eg. `join -a1 <file_of_fasta_accesions> ref2taxid.tsv`

**Comment by eparisis** [comment]
Thanks a lot for your help. Unfortunately the file didn't include the correct accession number but I found I way to create the ref2taxid file.

I firstly fetched my taxIDs from my reference fasta file I created earlier using:
```bash
awk '/>/ {print $1}' reference.fna | cut -c 2- > accessions
```
and then using NCBI's entrez toolkit I fetched the TaxIDs:
```bash
cat accessions | epost -db nuccore | esummary -db nuccore | xtract -pattern DocumentSummary -element AccessionVersion,TaxId > ref2taxid.tsv
```
The workflow did run successfully after that and it gave me some alignments!

If possible it would be nice if in the next version you could add the `assignments.tsv` and the `lineages.txt` in the workflows output folder as well as the `assignments.tsv` for the Kraken2 workflow.

**Comment by f3dja** [comment]
Lately I ran into a similar problem; however due to the sheer amount of missing accessions (>200000) I had to split my queries and wrote a little R script:
```
library(tidyverse)

##
#setwd("~/more/ncbi/")


### which accessions are missing?
if (!file.exists("missing.txt")) {
  ## make ref2taxid.targloci.tsv
  ## pigz -dc accession2taxid/nucl_gb.accession2taxid.gz | awk -F '\t' '{print $2,$3}' | sed -e 's/ /\t/g' | tail -  -n +2 > accession2taxid/ref2taxid.targloci.tsv
  all_accessions_of_nucl_gb<-readr::read_delim(file="accession2taxid/ref2taxid.targloci.tsv",delim="\t",col_names=c("accessionid","taxid"))
  
  ## pigz -dc nt.gz | grep '>' | awk -F '>| ' '{print $2}' > accessions.txt
  all_accessions_of_nt<-readr::read_delim(file="accessions.txt",delim="\t",col_names=c("accessionid"))
  
  ## missing accessions
  acc <- all_accessions_of_nt %>% anti_join(all_accessions_of_nucl_gb)
  write_csv(acc,file="missing.txt")
}
### /

### get missing accessions
acc<-readr::read_csv("missing.txt")

if (file.exists("acc2taxid.temp.rds")) {
  prevdf <- readRDS("acc2taxid.temp.rds") %>%              ## read previously fetched accessions
    inner_join(acc,by=c("AccessionVersion"="accessionid")) ## only really missing accessions
  acc<-acc %>% anti_join(prevdf, by=c("accessionid"="AccessionVersion")) ## only still missing
} else {
  prevdf <- NULL
}

acclist<-split(acc$accessionid,ceiling(seq_along(acc$accessionid)/200))

###
tempdf<-prevdf
acc2taxid <- lapply(acclist, function(x) {
  
  temp<-reutils::esummary(x,"nuccore")
  
  retcount=0
  while (!temp$errors$all_empty() & retcount < 100) {
    retcount=retcount+1
    cat(paste0(retcount,". retry\n"))
    temp<-reutils::esummary(x,"nuccore")
  }
  if (retcount == 100) {
    writexl::write_xlsx(
      list(query=x,result=XML::xmlToDataFrame(temp$xmlSet("//DocumentSummary"))),
      path = paste0("persisting error at block ",parent.frame()$i[],".xlsx"))
  }
  
  accqresult<-XML::xmlToDataFrame(temp$xmlSet("//DocumentSummary"))
  
  ## temp data (as fallback)
  tempdf <<- tempdf %>% bind_rows(accqresult) ## write to variable in outer scope to save temp data
  if (parent.frame()$i[] %% 20 == 0) saveRDS(tempdf, file="acc2taxid.temp.rds")

  return((accqresult))}
)

qresdf<-prevdf %>% bind_rows(do.call(bind_rows,acc2taxid))

saveRDS(qresdf, file="acc2taxid.rds")
#writexl::write_xlsx(qresdf, path="acc2taxid.xlsx")

new_ref2taxid <- qresdf %>% select(AccessionVersion,TaxId) %>% dplyr::rename(accessionid=AccessionVersion, taxid=TaxId)
write_delim(new_ref2taxid,file="new_ref2taxid.targloci.tsv",delim = "\t",col_names = F)

full_ref2taxid <- all_accessions_of_nucl_gb %>% bind_rows(new_ref2taxid %>% mutate(taxid=as.numeric(taxid)))
write_delim(full_ref2taxid,file="accession2taxid/full_ref2taxid.targloci.tsv",delim = "\t",col_names = F)

```

Hope this might help somebody.
