### ISSUE TITLE
[Bug]: Numpy version

### ISSUE THREAD

**Issue by thecorz** [epi2me-labs/wf-metagenomics#36]
### What happened?

Numpy is complaining about the c components. It might be a version issue. It's the first time I encounter this error. I don't know if to do with how the dependencies are managed in the container. Error message and traceback below:

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

2.0.8

### Relevant log output

```shell
Error executing process > 'kraken_pipeline:kraken2_client (27)'

Caused by:
  Process `kraken_pipeline:kraken2_client (27)` terminated with an error exit status (1)

Command executed:

  fastcat         -a "0"                  -s "CB0981_35_cycle_ITS"         -r "CB0981_35_cycle_ITS.27.stats"         "CB0981_35_cycle_ITS.fastq" > filtered.fastq
  fastcat_histogram.py         --sample_id "CB0981_35_cycle_ITS"         "CB0981_35_cycle_ITS.27.stats" "CB0981_35_cycle_ITS.27.json"
  
  kraken2_client         --port 8080 --report report.txt         --sequence filtered.fastq > "CB0981_35_cycle_ITS.kraken2.assignments.tsv"
  tail -n +1 report.txt > "CB0981_35_cycle_ITS.kraken2.report.txt"

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
      from . import multiarray
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
      from . import overrides
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: PyCapsule_Import could not import module "datetime"
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/concertbio/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/fastcat_histogram.py", line 8, in <module>
      import numpy as np
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
      from . import core
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
      raise ImportError(msg)
  ImportError: 
  
  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
  
  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.
  
  We have compiled some common reasons and troubleshooting tips at:
  
      https://numpy.org/devdocs/user/troubleshooting-importerror.html
  
  Please note and check the following:
  
    * The Python version is: Python3.8 from "/home/epi2melabs/conda/bin/python"
    * The NumPy version is: "1.23.5"
  
  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.
  
  Original error was: PyCapsule_Import could not import module "datetime"

Work dir:
  

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by cjw85** [comment]
Closing due to lack of response.
