### ISSUE TITLE
[Bug]: Kraken Pipeline Make Report Terminated with Error

### ISSUE THREAD

**Issue by MetaGJezzy** [epi2me-labs/wf-metagenomics#42]
### What happened?

The metagenomics workflow will run for a period of time and start generating the html to visualize the kraken2 results and then stop with error without analyzing all of the data.  Sometimes it will error out immediately and sometime it will error out 1/2 way through.  

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

EPI2ME Labs V4.1.2

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v2.0.8

### Relevant log output

```shell
[5a/2ddc4e] Submitted process > kraken_pipeline:progressive_bracken (348)
[cb/5ec6ee] Submitted process > kraken_pipeline:output (348)
[10/b78d93] Submitted process > kraken_pipeline:makeReport (348)
[6e/ac83c4] Submitted process > kraken_pipeline:progressive_bracken (349)
[17/50a6cb] Submitted process > kraken_pipeline:output (349)
[85/a10537] Submitted process > kraken_pipeline:makeReport (349)
[58/f00d3a] Submitted process > kraken_pipeline:progressive_bracken (350)
[10/1cbfca] Submitted process > kraken_pipeline:output (350)
[44/cb9be5] Submitted process > kraken_pipeline:makeReport (350)
[1d/e44c6d] Submitted process > kraken_pipeline:progressive_bracken (351)
[aa/9608f8] Submitted process > kraken_pipeline:output (351)
Error executing process > 'kraken_pipeline:makeReport (350)'
Caused by:
  Process `kraken_pipeline:makeReport (350)` terminated with an error exit status (1)
Command executed:
  report.py         "wf-metagenomics-report.html"         --versions versions         --params params.json         --summaries all_stats.350         --lineages "bracken.350"         --vistempl template.html
Command exit status:
  1
Command output:
  (empty)
Command error:
  Traceback (most recent call last):
    File "/home/pasteur/epi2melabs/workflows/epi2me-labs/wf-metagenomics/bin/report.py", line 187, in <module>
      main()
    File "/home/pasteur/epi2melabs/workflows/epi2me-labs/wf-metagenomics/bin/report.py", line 174, in main
      kraken(args.summaries[0], section)
    File "/home/pasteur/epi2melabs/workflows/epi2me-labs/wf-metagenomics/bin/report.py", line 47, in kraken
      lbins, lcounts = list(zip(*len_hist))
  ValueError: not enough values to unpack (expected 2, got 0)
Work dir:
  /home/pasteur/epi2melabs/instances/wf-metagenomics_2789f280-5845-4ae4-a505-5db33d9037da/work/44/cb9be55f8c748e639aa25f2b39ff8c
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by nggvs** [comment]
Hi, 
Thank you for using the workflow. Could you paste the command? Might you have used the option 
--batch size 1?

**Comment by nggvs** [comment]
Closing due to lack of response.
