### ISSUE TITLE
`kraken_pipeline:makeReport` fails when using --amr option - [ Plotter   ] Cannot correct axis labels in complicated scenarios.

### ISSUE THREAD

**Issue by eparisis** [epi2me-labs/wf-metagenomics#77]
### Operating System

Ubuntu 22.04

### Workflow Version

v2.5.0

### Workflow Execution

Command line

### CLI command run

`nextflow run epi2me-labs/wf-metagenomics --fastq data/fastq/ --database local/dbs/PLUSPF8 --amr -r v2.5.0`

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

The workflow runs fine when running `kraken2` but as soon as I add the `--amr` option it fails at the `kraken_pipeline:makeReport` step. I tried using different fastq files and the thing is it works on half of our runs and fails at some others. Sequencing procedure is same on all runs and we use the same kits so the `fastq` files are similar in each run. I cant find any major differences on the input files and why it works for some inputs but on others it fails.

The main error message seems to be in a python script: `[Plotter   ] Cannot correct axis labels in complicated scenarios.`

### Relevant log output

```shell
executor >  local (75)
[59/df792e] process > fastcat (4)                                    [100%] 10 of 10 ✔
[b4/dc0efc] process > kraken_pipeline:unpackTaxonomy                 [100%] 1 of 1 ✔
[6c/4cb3da] process > kraken_pipeline:unpackDatabase                 [100%] 1 of 1 ✔
[18/da4c9a] process > kraken_pipeline:determine_bracken_length       [100%] 1 of 1 ✔
[f3/c6a45d] process > kraken_pipeline:kraken_server                  [  0%] 0 of 1
[5d/8fb19a] process > kraken_pipeline:run_common:getVersions         [100%] 1 of 1 ✔
[27/320ff2] process > kraken_pipeline:run_common:abricateVersion     [100%] 1 of 1 ✔
[bc/b79171] process > kraken_pipeline:run_common:getParams           [100%] 1 of 1 ✔
[c8/077a0c] process > kraken_pipeline:kraken2_client (9)             [ 80%] 8 of 10
[4a/1295da] process > kraken_pipeline:progressive_stats (8)          [ 87%] 7 of 8
[10/bb3ecf] process > kraken_pipeline:progressive_kraken_reports (8) [ 87%] 7 of 8
[93/807995] process > kraken_pipeline:progressive_bracken (5)        [ 80%] 4 of 5
[d9/246788] process > kraken_pipeline:run_amr:abricate (9)           [ 80%] 8 of 10
[c6/b8b96b] process > kraken_pipeline:run_amr:abricate_json (8)      [ 87%] 7 of 8
[31/7043f1] process > kraken_pipeline:run_amr:progressive_amr (4)    [ 75%] 3 of 4
[35/f6a761] process > kraken_pipeline:makeReport (2)                 [ 66%] 2 of 3, failed: 1
[-        ] process > kraken_pipeline:concatAssignments              -
[b8/911e2f] process > kraken_pipeline:output (3)                     [100%] 3 of 3 ✔
[-        ] process > kraken_pipeline:stop_kraken_server             -
ERROR ~ Error executing process > 'kraken_pipeline:makeReport (2)'

Caused by:
  Process `kraken_pipeline:makeReport (2)` terminated with an error exit status (1)

Command executed:

  workflow-glue report         "wf-metagenomics-report.html"         --workflow_name wf-metagenomics         --versions versions         --params params.json         --stats all_stats.2         --lineages "bracken.2"         --taxonomic_rank "S"         --abundance_threshold "0"        --n_taxa_barplot "8"        --amr amr.2.barcode06

Command exit status:
  1

Command output:
  (empty)

Command error:
  [13:39:00 - matplotlib.font_manager] generated new fontManager
  [13:39:00 - workflow_glue] Starting entrypoint.
  [13:39:01 - Plotter   ] Skipping axis label fixing
  [13:39:01 - Plotter   ] Skipping axis label fixing
  [13:39:01 - Plotter   ] Skipping axis label fixing
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  [13:39:01 - Plotter   ] Cannot correct axis labels in complicated scenarios.
  /home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: divide by zero encountered in log
    result = getattr(ufunc, method)(*inputs, **kwargs)
  Traceback (most recent call last):
    File "/home/DNAUserseq/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/DNAUserseq/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/home/DNAUserseq/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/workflow_glue/report.py", line 386, in main
      amr_data = report_utils.parse_amr(args.amr)
    File "/home/DNAUserseq/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/workflow_glue/report_utils/report_utils.py", line 362, in parse_amr
      data = json.load(fh)
    File "/home/epi2melabs/conda/lib/python3.8/json/__init__.py", line 293, in load
      return loads(fp.read(),
    File "/home/epi2melabs/conda/lib/python3.8/json/__init__.py", line 357, in loads
      return _default_decoder.decode(s)
    File "/home/epi2melabs/conda/lib/python3.8/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/home/epi2melabs/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Work dir:
  /home/DNAUserseq/datadrive/wf-metagenomics-tests/workflows/amr_test/work/35/f6a761b3103a62f0244d7402bd4737

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

**Comment by nggvs** [comment]
Hi @eparisis ,
Thank you for using the pipeline! I'll try to reproduce your log. Could you check meanwhile if for those samples that fails there is an output from AMR and not empty files?

It should be here:
`/home/DNAUserseq/datadrive/wf-metagenomics-tests/workflows/amr_test/work/35/f6a761b3103a62f0244d7402bd4737`
and then  you'll find a symlink called `amr.*.barcode` that contains files called `barcodeXX_amr.json`?
Alternatively, you can check the folder `/home/DNAUserseq/datadrive/wf-metagenomics-tests/workflows/amr_test/work/31/7043f1...` where there shoud be the same file

Thank you very much in advance!

**Comment by eparisis** [comment]
Thanks for the quick reply! 

I reproduced the error again and found the files you asked for. 

I run 3 barcodes. Two of them have identified AMR genes in those `.json` files and one sample has no identified AMR genes and the `.json` file has this:
`{"barcode02": {"pass": false, "results": {}}}` 
but there are no empty files.

Running following command I also found the outputs from the AMR process, none of them are empty files:
```bash
$ find work/ -name "*_amr_results.tsv"
work/fd/2ab33cf03920edb3427fcc01285fc8/barcode03_amr_results.tsv
work/8a/3584e2e0860246eb63442a32b169f5/barcode01_amr_results.tsv
work/7b/04a9a16d5f7a874e35c7fd167bb332/barcode02_amr_results.tsv
work/20/c15c760ee5027dffc2a18eeb9267bd/barcode02_amr_results.tsv
work/c6/556c3fdf0adfc39019d364b25c98fd/barcode03_amr_results.tsv
work/db/2e32138798fadd326b9053410c451a/barcode01_amr_results.tsv
```

**Comment by nggvs** [comment]
Hi @eparisis 
Trying to reproduce the error, I've realized you are using v2.5.0. Is there any reason to use that version?

**Comment by eparisis** [comment]
I’ve been using this version for a while now, but if I’m not mistaken I tried it with the latest version too and had the same error. 

Also in the newer version you removed the executor options in the config file which lead to some errors with memory and cpu usage and I didn’t really have the time to troubleshoot that.

**Comment by nggvs** [comment]
Thank you for your answer, memory and resources will be also updated in the next release (in particular when using custom databases).
I had not been able to reproduce the error, would you mind to attach the amr_result files?

**Comment by nggvs** [comment]
Hi @eparisis,
I've tried to load those files and everything seems to be fine. However, the file that has failed according to your log is not there:
amr.2.barcode06, I've just seen barcode01, barcode02 and barcode03, have you also observed the error with these barcodes?

**Comment by eparisis** [comment]
Yes, Im sorry I wasnt clear on my previous comment. I reproduced the initial error with some other fastq files. Here is the relevant log for those exact results I attached you earlier. Let me know if you need anything else and thanks again for your time! 

[amr_nextflow.log](https://github.com/epi2me-labs/wf-metagenomics/files/14122862/amr_nextflow.log)

**Comment by nggvs** [comment]
Hi @eparisis ,
I was looking the files and I don't find anything weird, so probably is something else. Could you send me the content of the whole folder: `/home/DNAUserseq/datadrive/test/AMR/work/85/3689b54838e2c60211e3496ed2bdf9`

**Comment by eparisis** [comment]
Sure! 

[work_dir.zip](https://github.com/epi2me-labs/wf-metagenomics/files/14123946/work_dir.zip)

**Comment by nggvs** [comment]
Hi @eparisis ,
I've tried to use your files, but I'm still not able to reproduce your problem in my device. Is there anything in your configuration that you think may be useful to know? Could you see if with the latest version (it also fixes the custom db memory limitation) this problem persists, if it does, could you send me the same folder? 
The error is opening the JSON files from the AMR
```
amr_data = report_utils.parse_amr(args.amr)
    File "/home/DNAUserseq/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/workflow_glue/report_utils/report_utils.py", line 362, in parse_amr
      data = json.load(fh)
    File "/home/epi2melabs/conda/lib/python3.8/json/__init__.py", line 293, in load
      return loads(fp.read(),
    File "/home/epi2melabs/conda/lib/python3.8/json/__init__.py", line 357, in loads
      return _default_decoder.decode(s)
    File "/home/epi2melabs/conda/lib/python3.8/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/home/epi2melabs/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Apologies for the delay, I'm really trying to know which can be the reason

**Comment by eparisis** [comment]
Thanks for your effort!

I tried the newer version (`v2.9.0`) and it works fine!

After that I tried again to run those samples with `v2.5.0` and it failed again, so I guess it is fixed now with the newer version. 

As for the configuration I changed following options in `v2.5.0`:
`include_kraken2_assignments = true`
`database` I use a local version of the PlusPF8
`amr = true`
`amr_db` I tried `resfinder` and `card` and fails in both.

```bash
executor {
    $local {
        cpus = 16
        memory = "32 GB"
    }
}
```

**Comment by nggvs** [comment]
Hi @eparisis !
Glad to hear that the problem has been fixed with the new release!
Is there anything new failing/looking weird? If you find something else, please open an issue and I'll take a look. If it's fine for now, would you mind to close the issue?

Thank you very much for your patience!

**Comment by eparisis** [comment]
Thanks a lot!
